# Generated by Django 5.1.3 on 2025-02-04 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifttrak", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="rir",
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name="SetTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_number", models.IntegerField()),
                ("reps", models.IntegerField()),
                ("weight", models.FloatField(default=0.0)),
                ("rir", models.IntegerField(default=3)),
                (
                    "exercise_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lifttrak.exercisetemplate",
                    ),
                ),
            ],
        ),
    ]
