# Generated by Django 5.1.6 on 2025-02-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifttrak", "0003_workout_notes_alter_customexercise_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customexercise",
            name="muscles_targeted",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chest", "Chest"),
                    ("traps", "Traps"),
                    ("rhomboids", "Rhomboids"),
                    ("lats", "Lats"),
                    ("lower_back", "Lower Back"),
                    ("quadriceps", "Quadriceps"),
                    ("hamstrings", "Hamstrings"),
                    ("calves", "Calves"),
                    ("glutes", "Glutes"),
                    ("biceps", "Biceps"),
                    ("triceps", "Triceps"),
                    ("front_deltoid", "Front Deltoid"),
                    ("side_deltoid", "Side Deltoid"),
                    ("rear_deltoid", "Rear Deltoid"),
                    ("core", "Core"),
                    ("forearms", "Forearms"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="predefinedexercise",
            name="muscles_targeted",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chest", "Chest"),
                    ("traps", "Traps"),
                    ("rhomboids", "Rhomboids"),
                    ("lats", "Lats"),
                    ("lower_back", "Lower Back"),
                    ("quadriceps", "Quadriceps"),
                    ("hamstrings", "Hamstrings"),
                    ("calves", "Calves"),
                    ("glutes", "Glutes"),
                    ("biceps", "Biceps"),
                    ("triceps", "Triceps"),
                    ("front_deltoid", "Front Deltoid"),
                    ("side_deltoid", "Side Deltoid"),
                    ("rear_deltoid", "Rear Deltoid"),
                    ("core", "Core"),
                    ("forearms", "Forearms"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
