# Generated by Django 5.1.6 on 2025-02-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifttrak", "0005_workouttemplate_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="name",
            field=models.CharField(default="My Workout", max_length=100),
        ),
    ]
