# Generated by Django 5.1.6 on 2025-02-20 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifttrak", "0006_workout_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercisetemplate",
            name="custom_exercise",
        ),
        migrations.RemoveField(
            model_name="exercisetemplate",
            name="predefined_exercise",
        ),
        migrations.RemoveField(
            model_name="exercisetemplate",
            name="template",
        ),
        migrations.RemoveField(
            model_name="settemplate",
            name="exercise_template",
        ),
        migrations.RemoveField(
            model_name="set",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="workouttemplate",
            name="user",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="template",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="workout",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="date",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="name",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="notes",
        ),
        migrations.AddField(
            model_name="exercise",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="muscle_group",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="name",
            field=models.CharField(default="New Exercise", max_length=255),
        ),
        migrations.AddField(
            model_name="workout",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="My New Routine", max_length=255, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workout",
            name="routine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lifttrak.routine",
            ),
        ),
        migrations.CreateModel(
            name="RoutineExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lifttrak.exercise",
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routine_exercises",
                        to="lifttrak.routine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoutineSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reps", models.PositiveIntegerField(default=8)),
                ("weight", models.FloatField(default=0.0)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "routine_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="lifttrak.routineexercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lifttrak.exercise",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_exercises",
                        to="lifttrak.workout",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reps", models.PositiveIntegerField(default=8)),
                ("weight", models.FloatField(default=0.0)),
                ("completed", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "workout_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="lifttrak.workoutexercise",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CustomExercise",
        ),
        migrations.DeleteModel(
            name="PredefinedExercise",
        ),
        migrations.DeleteModel(
            name="ExerciseTemplate",
        ),
        migrations.DeleteModel(
            name="SetTemplate",
        ),
        migrations.DeleteModel(
            name="Set",
        ),
        migrations.DeleteModel(
            name="WorkoutTemplate",
        ),
    ]
