# Generated by Django 5.1.6 on 2025-02-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifttrak", "0007_remove_exercisetemplate_custom_exercise_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="started_at",
        ),
        migrations.AddField(
            model_name="workout",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
