# Generated by Django 5.1.6 on 2025-02-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifttrak", "0009_routine_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="name",
            field=models.CharField(
                blank=True, default="My Workout", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="muscle_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Chest", "Chest"),
                    ("Back", "Back"),
                    ("Legs", "Legs"),
                    ("Shoulders", "Shoulders"),
                    ("Arms", "Arms"),
                    ("Core", "Core"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
