# Generated by Django 5.1.6 on 2025-02-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifttrak", "0011_workout_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workout",
            old_name="notes",
            new_name="description",
        ),
        migrations.AddField(
            model_name="routineexercise",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
